### ISSUE TITLE
您好！关于这个项目请教一些问题？

### ISSUE THREAD

**Issue by topDreamer** [menghuanlater/Tianchi2020ChineseMedicineNER#3]
非常感谢作者开源这个项目！
第一，我使用这个项目用比赛的数据去跑的时候看着loss是没问题的，但是在每一轮验证的时候会如下的错误：
![image](https://user-images.githubusercontent.com/29766163/101279697-f06f9f00-37fe-11eb-815d-507f4c71ceb5.png)
然后我打印下s_seq[i][1]的值，发现都小于设置的"threshold": 0.45，导致分母为空获得的值如下截图：
![image](https://user-images.githubusercontent.com/29766163/101279734-3dec0c00-37ff-11eb-82c4-82b843cd5daa.png)
第二，我想问下您在设置滑动窗口的时候比如一段话可以使用滑动窗口分为两个segment的话，其中交叉的那部分信息若存在label的话，是没有在第二个segment标记出来吗？
感谢回答！

**Comment by menghuanlater** [comment]
1. 我记得我跑的时候第一次验证时p,r,f1值都在0.5以上，正常情况下除0是不应该出现的，我待会再跑一下看看
2. 是的，第二个段包含了一部分前序上文的信息，label是不会在这个段中标记出来的，但在训练时这部分是不加入损失计算的，所以是没有影响的


| |
安林
|
|
anlin781205936@126.com
|
签名由网易邮箱大师定制
在2020年12月6日 20:14，topDreamer<notifications@github.com> 写道：

非常感谢作者开源这个项目！
第一，我使用这个项目用比赛的数据去跑的时候看着loss是没问题的，但是在每一轮验证的时候会如下的错误：

然后我打印下s_seq[i][1]的值，发现都小于设置的"threshold": 0.45，导致分母为空获得的值如下截图：

第二，我想问下您在设置滑动窗口的时候比如一段话可以使用滑动窗口分为两个segment的话，其中交叉的那部分信息若存在label的话，是没有在第二个segment标记出来吗？
感谢回答！

**Comment by menghuanlater** [comment]
@topDreamer 我重新跑了下，我把batch_size下调到12了(手里暂时只有一张卡)，第200步的验证结果为：
p:0.6768  r=0.2611  f1=0.3769
不知道你设置的batch_size是多少，如果bsz设置的比较小的话，建议增加验证间隔，我把完整的项目文件放在了网盘，链接为：
链接：https://pan.baidu.com/s/11ndDrdpzEixFRRLqyUMVOA 
提取码：x8fh

**Comment by topDreamer** [comment]
收到！非常感谢回复！因为用的是roberta模型，单卡的话batchsize最大只能给到4左右（我猜你的应该是V100哈哈~），我想您建议的”增加验证间隔“的试试看，感觉是这个问题，一会把eval_interval调大一些重新跑跑~
